### ISSUE TITLE
map contents got shrunk

### ISSUE THREAD

**Issue by frommainland** [NocheVolta/FramerMapboxJS#5]
Hello, the map contents loaded in iPhone framer app will appear shrunk and map labels are 50% smaller than usual. Set 'Framer.Device.contentScale = 2' in framer won't work, either.

Please take a look at the screenshot, thank you.
![img_6277](https://user-images.githubusercontent.com/29867242/40577322-729f6fde-6136-11e8-9c01-251e96f125aa.PNG)

**Comment by NocheVolta** [comment]
This is related on how Mapbox paints the map, I think it uses the `devicePixelRatio` to set those values/weights. On retina displays (using default resolution) or opening the map directly in the browser should fix it.
